---
- hosts: localhost
  become: yes
  vars:
    - src_dir: src
    - work_dir: work

  tasks:
    - dnf:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - mariadb-server
        - mariadb
        - mariadb-devel

    - name: start mariadb and enabled
      service: name=mariadb state=started enabled=yes

  handlers:
