---
- hosts: localhost
  become: yes
  vars:
    - src_dir: src
    - work_dir: work

  tasks:
    - name: install remi repository
      command: rpm -Uvh --force http://rpms.famillecollet.com/enterprise/remi-release-8.rpm

    - name: install php
      dnf:
        name: "{{ packages }}"
        state: present
        enablerepo: remi
        disablerepo: remi-safe
      vars:
        packages:
        - php80 
        - php80-php-common
        - php80-php-pdo
        - php80-php-cli
        - php80-php-mbstring
        - php80-php-gd
        - php80-php-intl
        - php80-php-xml
        - php80-php-pecl-mcrypt
        - php80-php-mysqlnd
        - php80-php-ldap
        - php80-php-pecl-xdebug3
        - php80-php-gmp
        - php80-php-devel

    - name: update-alternatives
      command: update-alternatives --install /usr/bin/php php /usr/bin/php80 1

    - name: restart httpd
      service: name=httpd state=restarted

  handlers:

