---
- hosts: localhost
  become: yes
  vars:
    - src_dir: src
    - work_dir: work

  tasks:
    # pdftotext を使いたい
    - name: install poppler
      dnf: name=poppler state=latest
    - name: install poppler-utils
      dnf: name=poppler-utils state=latest

    # gs を使いたい
    - name: install ghostscript
      dnf: name=ghostscript state=latest

  handlers:
